### ISSUE TITLE
General Improvements

### ISSUE THREAD

**Issue by Yuri-Lima** [Yuri-Lima/SharePay#21]
@deansville You can type something here or attach documents, print screens... anything that you want to someone take a look at.

**Comment by deansville** [comment]
- [x] Done
@deansville 

The following points need reviewing/changing 

- Website Title = SharePay House Bills --> This is currently Hourse Bills
![image](https://user-images.githubusercontent.com/76538817/122466210-eb12be80-cfb0-11eb-904f-01f8d37b8ddb.png)

- Website subtitle = Group house bills causing a problem? Not anymore! Sign up and lets break it down! --> Share how much each house mates will pay in June 2021! Sign up and lets break it down!
![image](https://user-images.githubusercontent.com/76538817/122466752-9d4a8600-cfb1-11eb-8683-ecc4856266cb.png)

**Comment by deansville** [comment]
- [x] Done
@deansville 

![image](https://user-images.githubusercontent.com/76538817/122466990-e1d62180-cfb1-11eb-8662-a455535ca294.png)

- Text --> Thank you for joining us --> Thank You for Join Us


- Image background/foreground --> This would benefit from some colour contrast or the text being a darker grey colour with text stating House Bills

![image](https://user-images.githubusercontent.com/76538817/122467245-35486f80-cfb2-11eb-9d3d-d26328b6d845.png)

**Comment by deansville** [comment]
- [x] Done
@deansville 

![image](https://user-images.githubusercontent.com/76538817/122468750-016e4980-cfb4-11eb-9dec-8555ed858db6.png)

- Please provide us with the following: --> Existing text = Please, Provide to us:

![image](https://user-images.githubusercontent.com/76538817/122469048-62961d00-cfb4-11eb-9007-c9a62cdcc732.png)

- Insert total value of the bill --> existing text = Add a Value of Bill

- Total value of bill: --> existing text = what is the value's bill:

- Select period of the bill: --> existing text = What is the bill's period?

- Start:        End: --> existing text =     From:        End:

**Comment by deansville** [comment]
- [x] Done
@deansville 

I am sure you are aware of this error, but listed anyways. 

![image](https://user-images.githubusercontent.com/76538817/122470251-bd7c4400-cfb5-11eb-9706-f379e0490c1f.png)

**Comment by Yuri-Lima** [comment]
ALL DONE.

@deansville
