### ISSUE TITLE
Marketing - SharePay Main Video

### ISSUE THREAD

**Issue by nairaromero** [Yuri-Lima/SharePay#25]
This is the main video that will show the user in a simple way what is SharePay.
https://www.youtube.com/watch?v=uuAUG4-uKy4

**Comment by Yuri-Lima** [comment]
Lets make some properly title and descriptions for each video. As you can see below there arent any informarions. @nairaromero 
![Screenshot from 2021-06-24 09-57-42](https://user-images.githubusercontent.com/9964218/123267054-f430ed80-d4d2-11eb-8454-5517bfee64d8.png)
