### ISSUE TITLE
Changing logins logo

### ISSUE THREAD

**Issue by Yuri-Lima** [Yuri-Lima/SharePay#30]
![Screenshot_20210615-142133_Samsung Internet.jpg](https://user-images.githubusercontent.com/9964218/122096682-32e4ea80-cde5-11eb-8a51-a854f820df87.jpg)

**Comment by deansville** [comment]
![Dog](https://user-images.githubusercontent.com/76538817/122464468-c87fa600-cfae-11eb-8e4b-b244f02cdb72.PNG)

**Comment by deansville** [comment]
![dog 2](https://user-images.githubusercontent.com/76538817/122465332-e568a900-cfaf-11eb-8da1-3070ebe65d65.PNG)

**Comment by Yuri-Lima** [comment]
DONE
